# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-18 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='liked_books',
            field=models.ManyToManyField(related_name='favorite_books', to='favorite_books_app.User'),
        ),
    ]
